In [3]:
#🌟 Exercise 1 : Array Creation and Manipulation
# Instructions
# Create a 1D NumPy array containing numbers from 0 to 9.

import numpy as np

# Create a 1D NumPy array containing numbers from 0 to 9
array_1d = np.arange(10)

array_1d


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#🌟 Exercise 2 : Type Conversion and Array Operations
# Instructions
# Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

my_list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(my_list, dtype=int)
my_array

array([3, 2, 0, 1, 2])

In [5]:
# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays
# Instructions
# Create a 3x3 NumPy array with values ranging from 1 to 9.

# Create a 3x3 NumPy array with values ranging from 1 to 9
array_3x3 = np.arange(1, 10).reshape(3, 3)

array_3x3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
# Create a 2D NumPy array of shape (4, 5) filled with random numbers
random_array = np.random.randint(0, 50, size=(4, 5))

random_array


array([[24, 47, 45, 14, 35],
       [27, 45, 38, 40, 33],
       [21,  9, 34, 32, 34],
       [14,  5,  4, 19, 18]])

In [8]:
# 🌟 Exercise 5 : Indexing Arrays

# Select the second row from a given 2D NumPy array.

# Example 2D array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Select the second row (index 1)
second_row = my_2d_array[1, :]  # or my_2d_array[1]

second_row


array([4, 5, 6])

In [9]:
# 🌟 Exercise 6 : Reversing elements
# Instructions
# Reverse the order of elements in a given 1D NumPy array (first element becomes last).

# Reverse the order of elements in the array_1d
reversed_array = my_array[::-1]

reversed_array


array([2, 1, 0, 2, 3])

In [10]:
# 🌟 Exercise 7 : Identity Matrix
# Instructions
# Create a 4x4 identity matrix using NumPy.

identity_matrix = np.eye(4)

identity_matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
# prompt:  Simple Aggregate Funcs
# Find the sum and average of a given 1D array.

# Calculate the sum of array_1d, made in exercize 1
array_sum = np.sum(array_1d)
print(f"Sum of array_1d: {array_sum}")

# Calculate the average of array_1d
array_average = np.mean(array_1d)
print(f"Average of array_1d: {array_average}")


Sum of array_1d: 45
Average of array_1d: 4.5


In [14]:
# 🌟 Exercise 9 : Create Array and Change its Structure
# Instructions
# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.


# Create a NumPy array with elements from 1 to 20
array_3 = np.arange(1, 21)

# Reshape the array into a 4x5 matrix
reshaped_array = array_3.reshape(4, 5)

# Print the reshaped array
reshaped_array


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
# 🌟 Exercise 10 : Conditional Selection of Values
# Instructions
# Extract all odd numbers from a given NumPy array.

# Extract all odd numbers from array_1d
odd_numbers = array_1d[array_1d % 2 != 0]

print(f"Odd numbers in array_1d: {odd_numbers}")


Odd numbers in array_1d: [1 3 5 7 9]
